@startuml
'https://plantuml.com/sequence-diagram



title DispatcherServlet初始化流程

autonumber
actor "Spring Framework" as framework

participant AbstractApplicationContext.java as AbContext
participant ApplicationListener as Listener
participant FrameworkServlet as FServlet
participant DispatcherServlet as dispatcher


framework -> AbContext: refresh()
AbContext -> AbContext: finishRefresh()
AbContext -> AbContext: publishEvent()
note left
- 刷新容器时，触发。
- spring事件机制（观察者模式）
end note
AbContext -> Listener: onApplicationEvent()
Listener -> FServlet: onApplicationEvent()
note left
- ApplicationListener（观察者）
- FrameworkServlet.ContextRefreshListener
- 作为内部类（具体观察者）实现其接口
end note
FServlet -> dispatcher: onRefresh()
dispatcher -> dispatcher: initStrategies()
note left
SpringMVC的九大组件给初始化
initMultipartResolver(context);
initLocaleResolver(context);
initThemeResolver(context);
initHandlerMappings(context);
initHandlerAdapters(context);
initHandlerExceptionResolvers(context);
initRequestToViewNameTranslator(context);
initViewResolvers(context);
initFlashMapManager(context);
end note


@enduml