@startuml
'https://plantuml.com/class-diagram


title spring 事件驱动,采用观察者模式
'spring 入口
'org.springframework.context.support.AbstractApplicationContext.refresh


' todo 未完全理解
'
'主题（Subject）：也称为被观察者或可观察者，它是具有状态的对象，
'并维护着一个观察者列表。
'主题提供了添加、删除和通知观察者的方法。
abstract class ApplicationEvent {
}
note left: 被观察者 (主题)

abstract class ApplicationContextEvent extends ApplicationEvent{
}

class ContextRefreshedEvent extends ApplicationContextEvent{

}
class ContextClosedEvent extends ApplicationContextEvent{

}

class ContextStartedEvent extends ApplicationContextEvent{

}
class ContextStoppedEvent extends ApplicationContextEvent{

}

'具体主题（Concrete Subject）：具体主题是主题的具体实现类。
'它维护着观察者列表，并在状态发生改变时通知观察者。

class SimpleApplicationEventMulticaster{
multicastEvent()
'org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(org.springframework.context.ApplicationEvent, org.springframework.core.ResolvableType)
}
note left: 具体主题

'观察者（Observer）：观察者是接收主题通知的对象。
'观察者需要实现一个更新方法，当收到主题的通知时，调用该方法进行更新操作。


interface ApplicationListener<E extends ApplicationEvent>{
onApplicationEvent{}
}
note left: 观察者



'具体观察者（Concrete Observer）：具体观察者是观察者的具体实现类。
'它实现了更新方法，定义了在收到主题通知时需要执行的具体操作。
class ContextRefreshListener implements ApplicationListener<ContextRefreshedEvent>{
onApplicationEvent()
}
note left: 具体观察者

abstract class AbstractApplicationContext implements ConfigurableApplicationContext{
refresh()
finishRefresh()
publishEvent()
}
interface ConfigurableApplicationContext extends ApplicationContext{
publishEvent()
}
interface ApplicationContext implements ApplicationEventPublisher{
publishEvent()
}

interface ApplicationEventPublisher {
publishEvent()
}

AbstractApplicationContext -->SimpleApplicationEventMulticaster:发布
SimpleApplicationEventMulticaster -->ContextRefreshListener:通知
ApplicationListener --> ContextRefreshedEvent:监听

'参考：https://blog.csdn.net/u022812849/article/details/124530419
'https://blog.csdn.net/qq_46611668/article/details/120072492
@enduml