@startuml
'https://plantuml.com/class-diagram
'因为 Java 与咖啡之间的联系，
'所以咖啡的原材料咖啡豆（Java Bean）
'就自然而然地成为了 Spring 中代
'表一种基本单元的名称。
'Spring源码中的抽象工厂模式
'todo https://blog.csdn.net/zhouwenxiamg/article/details/138059163

interface BeanFactory {
    + Object getBean()
}

interface ListableBeanFactory extends BeanFactory {
    + Object createBean()
}
interface HierarchicalBeanFactory extends BeanFactory {
    + Object createBean()
}

interface ConfigurableBeanFactory extends HierarchicalBeanFactory {
    + Object createBean()
}

interface AbstractBeanFactory implements ConfigurableBeanFactory {
    + Object createBean()
}



interface ApplicationContext extends ListableBeanFactory{
    + Object getBean()
}

interface ConfigurableListableBeanFactory extends ListableBeanFactory{
+ Object createBean()
}

class DefaultListableBeanFactory implements ConfigurableListableBeanFactory {
+ Object createBean()
}





@enduml

