plugins {
    id 'java'
}

group 'org.springframework'
version '5.1.13.BUILD-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    optional(project(":spring-context"))
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.2'
    // https://mvnrepository.com/artifact/org.postgresql/postgresql
    implementation("org.postgresql:postgresql:42.1.4")
}

test {
    useJUnitPlatform()
}